plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}


android {
    namespace 'com.example.langhexx'
    compileSdk 34
    lintOptions {
        disable 'HardcodedText' // Disable check for hardcoded strings
        check 'NewApi'        // Ensure specific API checks are enabled
        abortOnError true     // Make the build fail if any lint error is found
        htmlOutput file("lint-report.html") // Generate an HTML report
    }
    buildFeatures {
        buildConfig = true
    }
    defaultConfig {
        applicationId "com.example.langhexx"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        Properties properties = new Properties()
        properties.load(project.rootProject.file('local.properties').newDataInputStream())
        buildConfigField "String", "OPENAI_API_KEY", "\"${properties.getProperty('OPENAI_API_KEY')}\""
        buildConfigField "String", "AZURE_TTS_API_KEY", "\"${properties.getProperty('AZURE_TTS_API_KEY')}\""
        buildConfigField "String", "GEMINI_API_KEY  ", "\"${properties.getProperty('GEMINI_API_KEY')}\""
        buildConfigField "String", "AZURE_STT_API_KEY  ", "\"${properties.getProperty('AZURE_STT_API_KEY')}\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    sourceSets {
        main {
            res {
                srcDirs 'src\\main\\res', 'src\\main\\res\\values-en'
            }
        }
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-auth:20.7.0'
    implementation 'com.google.firebase:firebase-auth:22.1.2'
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.activity:activity:1.8.0'
    implementation 'com.google.android.gms:play-services-auth:21.3.0'
    implementation 'com.google.firebase:firebase-crashlytics-buildtools:3.0.3'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.8.22")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1")
    implementation platform('com.google.firebase:firebase-bom:33.5.1')
    implementation("com.google.firebase:firebase-auth")
    implementation("com.google.firebase:firebase-database")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation ("com.android.volley:volley:1.2.1")
    implementation ("com.github.bumptech.glide:glide:4.16.0")
    annotationProcessor("com.github.bumptech.glide:compiler:4.16.0")
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.microsoft.cognitiveservices.speech:client-sdk:1.37.0'

    implementation 'com.google.code.gson:gson:2.10.1'

}